### PR TITLE
Rename binary to openmaptiles2mimir and make some place for tripadvisor

### PR DESCRIPTION
**Pull request by remi-dupre**
This is preliminary work before integrating the TripAdvisor importer.

I tried to move stuff very specific to existing importer in `sources/openmaptiles` (the idea will be to add a `source/tripadvisor`) and split some of the logic in more generic modules.

There is probably still some work to do in this direction, but I think the main structure is there and extra changes will come more naturally when trying to integrate TripAdvisor.

### CODE REVIEW

**Comment by remi-dupre** [comment]
@fatal69100 I think this has reached a reviewable state, I tried not to spread myself too thin.

**Comment by fatal69100** [comment]
@remi-dupre ok, do you mind if I do it monday ?

**Comment by remi-dupre** [comment]
> @remi-dupre ok, do you mind if I do it monday ?

No issue with that, I just wanted to notify you as I had already opened this PR quite early :wink:

**Review by fatal69100 — APPROVED** [review]
LGTM. Should we give a try to rust workspace (https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) ?

**Comment by remi-dupre** [comment]
> LGTM. Should we give a try to rust workspaces (https://doc.rust-lang.org/book/ch14-03-cargo-workspaces.html) ?

I don't think it would be a bad idea, but it doesn't seem critical, fafnir is still quite small and most of the compilation's pain actually comes from mimir which has a lot of dependencies (eg. we indirectly depend on warp, an entire web framework, there is probably some optimizations to do with that).

**Pull request merged**
